[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "go2_lidar"
version = "0.1.0"
requires-python = ">=3.10,<3.11"

[tool.setuptools]
packages = {find = {}}
